name: webring

services:
  webring:
    image: webring:latest
    container_name: webring
    restart: unless-stopped
    volumes:
      - ./log:/app/log
      - ./database:/app/database
    ports:
      - 127.0.0.1:5000:80
    environment:
      - FLASK_ENV=production
