[tool.poetry]
name = "Webring"
version = "1.2.1"
description = "Because everything on the Web eventually loops back onto itself."
authors = ["Caleb <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.2"
flask-smorest = "^0.44.0"
sys-vars = "^5.0.0"
gunicorn = "^22.0.0"
sqlalchemy = "^1.4.44"
flask-sqlalchemy = "^3.0.2"
requests = "^2.32.3"
flask-cors = "^4.0.1"
flask-db = "^0.4.1"

[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
pytest = "^8.2.2"
ruff = "^0.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
