[tool.poetry]
name = "Webring"
version = "1.2.0"
description = "Because everything on the Web eventually loops back onto itself."
authors = ["Caleb <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.2"
flask-smorest = "^0.40.0"
sys-vars = "^5.0.0"
gunicorn = "^20.1.0"
sqlalchemy = "^1.4.44"
flask-sqlalchemy = "^3.0.2"
requests = "^2.28.1"
flask-cors = "^3.0.10"
flask-db = "^0.3.2"

[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.991"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
