[tool.poetry]
name = "webring"
version = "0.1.0"
description = "Because."
authors = ["Caleb Ely <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.1"
flask-smorest = "^0.32.0"
sys-vars = "^4.0.0"
gunicorn = "^20.1.0"
SQLAlchemy = "^1.4.22"
Flask-SQLAlchemy = "^2.5.1"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
