[tool.poetry]
name = "Webring"
version = "1.1.2"
description = "Because everything on the Web eventually loops back onto itself."
authors = ["Caleb <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "2.1.3"
flask-smorest = "^0.32.0"
sys-vars = "^4.0.0"
gunicorn = "^20.1.0"
SQLAlchemy = "^1.4.22"
Flask-SQLAlchemy = "^2.5.1"
requests = "^2.26.0"
Flask-Cors = "^3.0.10"
Flask-DB = "^0.3.2"

[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.991"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
