"""Create LinkrotHistory model

Revision ID: bc15afca58dd
Revises: d22f2e10a5a3
Create Date: 2024-06-14 18:10:51.639104

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bc15afca58dd"
down_revision = "d22f2e10a5a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkrot_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_checked", sa.DateTime(), nullable=False),
        sa.Column("url_checked", sa.String(), nullable=False),
        sa.Column("was_alive", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["weblinks.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Audit log of linkrot checks.",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkrot_history")
    # ### end Alembic commands ###
